### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by atherdon** [karllhughes/side-project-sales#1]
- [ ] Right now link to this url(https://www.sideprojectchecklist.com/sales-checklist) get 404

- [ ] I think you need to add link to your forms, for collecting a sales only tools

**Comment by karllhughes** [comment]
@atherdon thanks! This isn't quite ready for general release (hoping to finish it up this weekend), hence the 404.

As for tools, I think the same form can work for both sales and marketing tools as they're pretty closely related, so I'll try that at first. If it gets messy, I'll build another form, but currently I only get a few submissions per week so it's pretty easy to sort out.
