### ISSUE TITLE
Can you add an anchors to each headline?

### ISSUE THREAD

**Issue by atherdon** [karllhughes/side-project-sales#3]
Just wanted to share link about how to message a people and want to have a direct link into the "Direct Outreach" section

**Comment by karllhughes** [comment]
Hey @atherdon good idea. You actually can do a link like that: https://www.sideprojectchecklist.com/sales-checklist/#direct-outreach

But, it's not clickable anywhere. I'll look into making those direct hyperlinks.

**Comment by atherdon** [comment]
Gotcha, @karllhughes - thank you! i think sub-anchor will be fine, just like markdown have...
